name: "Terratest GitHub Action"
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRATEST_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.TERRATEST_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  AWS_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  WEBHOOK_URL: ${{ secrets.PAGER_DUTY_TEST_CLOUDWATCH_URL }}
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.17)
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - name: Run go tests
        run: |
          cd test
          go mod download
          go clean -testcache
          go test -v -timeout 60m
